export const ACTION_TYPES = {
   // INITIAL_STATE: 'INITIAL_STATE',
   POST_REQUEST: 'POST_REQUEST',
   POST_SUCCESS: 'POST_SUCCESS',
   POST_FAILURE: 'POST_FAILURE',
   POST_STATE: 'POST_STATE',
   POST_NAME: 'POST_NAME',
   POST_USERNAME: 'POST_USERNAME',
   POST_EMAIL: 'POST_EMAIL',
};